### ISSUE TITLE
 InvalidSignatureException: Signature expired

### ISSUE THREAD

**Issue by dimpol** [hassy/artillery-dino#2]
InvalidSignatureException: Signature expired: 20160610T180547Z is now earlier than 20160610T180612Z (20160610T181112Z - 5 min.)\n    at Object.extractError (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n    at Request.extractError (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)\n    at Request.callListeners (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/request.js:596:14)\n    at Request.transition (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/request.js:37:9)\n    at Request.<anonymous> (/usr/local/lib/node_modules/artillery-dino/node_modules/aws-sdk/lib/request.js:598:12)'

Any thoughts?

**Comment by dimpol** [comment]
tried on clean ubuntu and clean kali linux ..with synced time  "sudo ntpdate ntp.ubuntu.com"
but the same error occurs
